language: node_js
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"

addons:
  postgresql: "9.3"

services:
  - postgresql

before_script:
  - psql -c 'create database "express-kvstore";' -U postgres

env:
  - PG_CONNECTION_STRING=postgres://postgres@localhost/express-kvstore
